name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint HTML, CSS & JS
        uses: super-linter/super-linter@v6
        with:
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JS: true